### Spring Boot Configuration ###
spring:
  # Database - MongoDB
  data:
    mongodb:
      host: ${app.db.host}
      database: ${app.db.database}
      port: ${app.db.port}

# Logging - alternative you can use logback with log rotation
logging.file: coffeeservice.log
logging:
  file:
    max-size: 1MB
    max-history: 10
  level:
    root: WARN
    org:
      springframework: INFO
    me:
      wirries:
        coffeemonitor:
          coffeeservice: DEBUG

## Application Configuration
# You can override this parameter with the program arguments
app:
  db:
    host: localhost
    database: coffeeservice
    port: 27017
  mqtt:
    url: tcp://localhost:1883
    topic: me/wirries/coffeesensor
    user:
    password:
    trustStore:
    trustStorePassword:
  web:
    user:
    password:
    cors:
      allowedOrigins:
